env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
parser: '@typescript-eslint/parser'
plugins:
  - mocha
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:mocha/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-param-reassign: 0
  consistent-return: 0
  mocha/no-mocha-arrows: off
  '@typescript-eslint/explicit-function-return-type': off
