env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
plugins:
  - mocha
extends:
  - airbnb-base
  - plugin:mocha/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-param-reassign: warn
  consistent-return: 0
  mocha/no-mocha-arrows: off
